# ./macros/Makefile.am

aclocaldir = $(datadir)/aclocal

dist_aclocal_DATA = \
	devkitpro.m4 \
	devkitpro_3ds.m4 \
	devkitpro_arm.m4 \
	devkitpro_ppc.m4 \
	devkitpro_wii.m4 \
	devkitpro_wut.m4 \
	wiiu_env_libbuttoncombo.m4 \
	wiiu_env_libcontentredirection.m4 \
	wiiu_env_libcurlwrapper.m4 \
	wiiu_env_libfunctionpatcher.m4 \
	wiiu_env_libkernel.m4 \
	wiiu_env_libmappedmemory.m4 \
	wiiu_env_libmocha.m4 \
	wiiu_env_libnotifications.m4 \
	wiiu_env_libromfs_wiiu.m4 \
	wiiu_env_librpxloader.m4 \
	wiiu_env_libsdutils.m4 \
	wiiu_env_libwuhbutils.m4 \
	wiiu_env_setup_lib.m4 \
	wiiu_env_wums.m4 \
	wiiu_env_wups.m4

